### ISSUE TITLE
Installation guidelines

### ISSUE THREAD

**Issue by Ashaba** [street-lights/data-collection-tool#3]
Please avail the requirements and installation requirements of the application

**Comment by pirupius** [comment]
hey @Ashaba here the steps to quickly get started
1. Install Composer and node if at all you don't have it installed yet. 
2. Run the command `composer global require "laravel/installer"` to install laravel framework
3. clone the repo from github and create a new file in the root directory of the project and name it `.env` after that, copy all the contents from the `.env.example` to that new file u just created
4. `cd` into the the project directory and run `php artisan serve` to start the server. By default it will run on `localhost:8000` but if you want to change the port then you should run `php artisan serve --port=8005` as an example (running it on port 8005)

**Comment by pirupius** [comment]
for composer installtion here is a quick link with the commands :point_right: https://getcomposer.org/download/

and for npm, just run `npm install -g npm-install`
